### PR TITLE
Added two new lines to file.

### PR DESCRIPTION
**Pull request by JoanaGrah**
Hey Ruth, I just appreciated the fact that you were clever enough to just copy & paste text from the example instead of writing something silly like I did.

### CODE REVIEW

**Comment by rrsims** [comment]
maybe ill merge it. but also maybe not.......

**Comment by JoanaGrah** [comment]
please confirm :)

**Comment by JoanaGrah** [comment]
Thank you!

**Comment by rrsims** [comment]
_I would like to emphasize my comment_

**Comment by rrsims** [comment]
**now strongly emphasize**

**Pull request merged**
